trigger:
- none

resources:
- repo: self

variables:
  imageRepository: 'amimagescantrivy'
  containerRegistry: 'formytrivytesting.azurecr.io'
  storageaccount: 'mytrivytesting'
  resourcegroup: 'Feb18'
  sacontainername: 'trivy-scan-reports1'
  serviceconn: 'Trivy-ACR-Serviceconnection' 
  target: $(build.artifactstagingdirectory)
  artifact: AM
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: BUILD
  displayName: Build and Push Stage
  jobs:
  - job: BUILD_JOB
    displayName: BUILD IMAGE
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: Docker@2
      displayName: BUILD AND PUSH IMAGE TO ACR
      inputs:
        containerRegistry: 'Trivy-ACR-Serviceconnection'
        repository: '$(imageRepository)'
        command: 'buildandpush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

######### Download and Install Aquasec Trivy:-

    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'SNYK-Service connection'
        testType: 'container'
        dockerImageName: '$(containerRegistry)/$(imageRepository):$(tag)'
        monitorWhen: 'always'
        failOnIssues: false