# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build job
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'bala-acr-SC'
              repository: 'balaacr05oct'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
          - task: CopyFiles@2
            inputs:
              SourceFolder: './kubernetes'
              Contents: '**.yml'
              TargetFolder: '$(build.artifactstagingdirectory)/manifests'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/manifests'
              ArtifactName: 'drop'
              publishLocation: 'Container'